- hosts: localhost
  vars_files:
  - secret.yml
  roles:
  - role: ec2
    ec2key: "ec2key"
    count: 3
    tag_name: "webserver"
    accesskey: "{{ akey }}"
    secretkey: "{{ skey }}"

  - role: ec2
    ec2key: "ec2key"
    count: 1
    tag_name: "loadbalancer"
    accesskey: "{{ akey }}"
    secretkey: "{{ skey }}"

- hosts: tag_Name_webserver
  roles:
  - webserver

- hosts: tag_Name_loadbalancer
  roles:
  - haproxy
